# Generated by Django 6.1 on 2026-08-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_school_name', models.CharField(blank=True, max_length=200)),
                ('primary_start_year', models.CharField(blank=True, max_length=10)),
                ('primary_end_year', models.CharField(blank=True, max_length=10)),
                ('secondary_school_name', models.CharField(blank=True, max_length=200)),
                ('secondary_start_year', models.CharField(blank=True, max_length=10)),
                ('secondary_end_year', models.CharField(blank=True, max_length=10)),
                ('advanced_secondary_school_name', models.CharField(blank=True, max_length=200)),
                ('advanced_secondary_start_year', models.CharField(blank=True, max_length=10)),
                ('advanced_secondary_end_year', models.CharField(blank=True, max_length=10)),
                ('university_name', models.CharField(blank=True, max_length=200)),
                ('university_degree', models.CharField(blank=True, max_length=200)),
                ('university_field', models.CharField(blank=True, max_length=200)),
                ('university_start_year', models.CharField(blank=True, max_length=10)),
                ('university_end_year', models.CharField(blank=True, max_length=10)),
                ('university_is_current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='api.profile')),
            ],
        ),
    ]
